In [1]:
import numpy as np

In [3]:
arr = np.array([12, 45, 67, 23])

In [5]:
arr

array([12, 45, 67, 23])

In [7]:
type(arr)

numpy.ndarray

In [9]:
arr

array([12, 45, 67, 23])

In [11]:
arr[2]

67

In [13]:
arr[2] = 100

In [15]:
arr

array([ 12,  45, 100,  23])

In [17]:
arr1 = np.array([23, 33.55, True, 'Pune'])

In [19]:
arr1

array(['23', '33.55', 'True', 'Pune'], dtype='<U32')

#### which one is faster ?

In [24]:
import time

In [36]:
time.time()

1750672284.1391425

In [38]:
s = 100000

l1 = list(range(s))

a1 = np.array(l1)

In [42]:
start_time = time.time()
x = [i * 2 for i in l1]
time_l = time.time() - start_time

print("time taken by list:", time_l)

time taken by list: 0.021564722061157227


In [44]:
start_time = time.time()
y = a1 * 2
time_arr = time.time() - start_time

print("time taken by list:", time_arr)

time taken by list: 0.0012617111206054688


In [46]:
time_l / time_arr

17.0916477702192

In [48]:
arr

array([ 12,  45, 100,  23])

In [50]:
arr.ndim

1

In [52]:
# arange

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(3, 15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
np.arange(-5, 5, 0.25)

array([-5.  , -4.75, -4.5 , -4.25, -4.  , -3.75, -3.5 , -3.25, -3.  ,
       -2.75, -2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75,
       -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,
        1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,
        4.  ,  4.25,  4.5 ,  4.75])

In [60]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
num = int(input("Enter the lucky no"))

lucky = np.random.randint(0, 100)
print("lucky no is:", lucky)
if num == lucky:
    print("Bingo")
else:
    print("What a panoti!!!")

Enter the lucky no 10


lucky no is: 88
What a panoti!!!


In [72]:
arr

array([ 12,  45, 100,  23])

In [74]:
np.mean(arr)

45.0

In [76]:
np.std(arr)

33.904277016329374

In [70]:
# 2-d arrays

In [78]:
arr1 = np.array([[1, 2, 3], [3, 2, 5], [5, 7, 1], [4, 10, 3]])

In [80]:
arr1

array([[ 1,  2,  3],
       [ 3,  2,  5],
       [ 5,  7,  1],
       [ 4, 10,  3]])

In [82]:
arr1.ndim

2

In [84]:
arr1.shape

(4, 3)

In [86]:
arr1.size

12

In [88]:
arr1.reshape(6, 2)

array([[ 1,  2],
       [ 3,  3],
       [ 2,  5],
       [ 5,  7],
       [ 1,  4],
       [10,  3]])

In [90]:
arr1.reshape(2,-1)

array([[ 1,  2,  3,  3,  2,  5],
       [ 5,  7,  1,  4, 10,  3]])

In [92]:
arr1

array([[ 1,  2,  3],
       [ 3,  2,  5],
       [ 5,  7,  1],
       [ 4, 10,  3]])

In [94]:
arr1.flatten()

array([ 1,  2,  3,  3,  2,  5,  5,  7,  1,  4, 10,  3])

In [96]:
arr1

array([[ 1,  2,  3],
       [ 3,  2,  5],
       [ 5,  7,  1],
       [ 4, 10,  3]])

In [98]:
arr1[1:3, 0:2]

array([[3, 2],
       [5, 7]])

In [100]:
arr1[2:, :]

array([[ 5,  7,  1],
       [ 4, 10,  3]])

In [102]:
# lin alg

In [104]:
a1 = np.array([[1, 3], [4, 5]])
a2 = np.array([[2, 3], [4, 5]])

In [110]:
a1

array([[1, 3],
       [4, 5]])

In [112]:
a2

array([[2, 3],
       [4, 5]])

In [114]:
a1 @ a2

array([[14, 18],
       [28, 37]])

In [116]:
np.linalg.det(a1)

-6.999999999999999

In [118]:
np.linalg.inv(a1)

array([[-0.71428571,  0.42857143],
       [ 0.57142857, -0.14285714]])

In [126]:
np.linalg.eig(a1)

EigResult(eigenvalues=array([-1.,  7.]), eigenvectors=array([[-0.83205029, -0.4472136 ],
       [ 0.5547002 , -0.89442719]]))

In [130]:
z = np.array([2, 4])  # vector

In [132]:
np.linalg.norm(z)

4.47213595499958